### ISSUE TITLE
Incorrect Teleport Behavior with Multiverse

### ISSUE THREAD

**Issue by elsell** [pmdevita/StayPut#7] opened 2020-06-24 00:07 UTC
I run a server with a few different worlds for different game modes. I also have a 'Lobby' world in which players spawn on join. This Lobby world and the main world/nether/end have shared inventories with Multiverse-Inventories. 

I desire for StayPut to put players back in their location ONLY in the main world named `world`. 

Thus I have entered this in the config:

```yaml
blacklisted-worlds:                                                             
  - spawn      # My Lobby World                                                                 
```

The plugin behaves correctly if I `/mvtp world` from `spawn`, however if I am in `world` and teleport to another world, let's say `creativeplots`, and THEN proceed to do `/lobby` (or `/mvtp spawn`), I am ultimately taken to `world` when I expect to be taken to `spawn`.

Here are the Multiverse debug messages showing this:

```python
19:58:10 INFO]: HiRANDY2 issued server command: /lobby  # Issuing command within creativeplots world

# First Multiverse World Change Event Messages

[19:58:10 INFO]: [Multiverse-Core-Debug] Got teleport event for player 'HiRANDY2' with cause 'PLUGIN'
[19:58:10 INFO]: [Multiverse-Core-Debug] Inferred sender 'null' from name 'null', fetched from name 'HiRANDY2'
[19:58:10 INFO]: [Multiverse-Core-Debug] Player 'HiRANDY2' was allowed to go to 'spawn' because enforceaccess is off.
[19:58:10 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'HiRANDY2' to go to 'spawn'.
[19:58:10 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2 traveling from world: cplots2 to world: spawn ===
[19:58:10 INFO]: [Multiverse-Inventories-Debug] No groups for fromWorld.
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Change affected by 1 fromProfiles and 1 toProfiles
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Persisted: ender_chest, inventory_contents, armor_contents, off_hand, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, last_location, potion_effects to WORLD:cplots2 (ProfileType:SURVIVAL) for player HiRANDY2
[19:58:10 INFO]: [Multiverse-Inventories-Debug] got data folder: plugins/Multiverse-Inventories/worlds/cplots2 from type: WORLD
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy

# At this point, the player is at the correct location in the lobby. 
# However, another teleport event is issued which takes the player back to the world World

[19:58:10 INFO]: [Multiverse-Core-Debug] Got teleport event for player 'HiRANDY2' with cause 'PLUGIN'
[19:58:10 INFO]: [Multiverse-Core-Debug] Inferred sender 'null' from name 'null', fetched from name 'HiRANDY2'
[19:58:10 INFO]: [Multiverse-Core-Debug] Player 'HiRANDY2' was allowed to go to 'world' because enforceaccess is off.
[19:58:10 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'HiRANDY2' to go to 'world'.
[19:58:10 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2 traveling from world: spawn to world: world ===
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Change affected by 1 fromProfiles and 0 toProfiles
[19:58:10 INFO]: [Multiverse-Inventories-Debug] No toProfiles...
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Persisted: ender_chest, inventory_contents, armor_contents, off_hand, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, last_location, potion_effects to WORLD:spawn (ProfileType:SURVIVAL) for player HiRANDY2
[19:58:10 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2's WORLD_CHANGE handling complete! ===
[19:58:10 INFO]: [Multiverse-Inventories-Debug] got data folder: plugins/Multiverse-Inventories/worlds/spawn from type: WORLD
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Updated: hit_points, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand for HiRANDY2 for GROUP:survival (ProfileType:SURVIVAL)
[19:58:10 INFO]: [Multiverse-Inventories-Debug] Defaulted: bed_spawn for HiRANDY2 for GROUP:survival (ProfileType:SURVIVAL)
[19:58:10 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2's WORLD_CHANGE handling complete! ===
[19:58:10 INFO]: [Multiverse-Core-Debug] Handling gamemode for player: HiRANDY2, Changing to SURVIVAL
[19:58:10 INFO]: [Multiverse-Core-Debug] From World: CraftWorld{name=world}
[19:58:10 INFO]: [Multiverse-Core-Debug] To World: {"MVWorld@138240882":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}
[19:58:10 INFO]: [Multiverse-Core-Debug] Handling gamemode for player: HiRANDY2, Changing to SURVIVAL
[19:58:10 INFO]: [Multiverse-Core-Debug] From World: CraftWorld{name=world}
[19:58:10 INFO]: [Multiverse-Core-Debug] To World: {"MVWorld@138240882":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}```

**Comment by pmdevita** [comment] 2020-06-24 00:46
Could you turn on debug mode in StayPut's config as well and send me what it outputs when you teleport to lobby/spawn? Thanks!

**Comment by elsell** [comment] 2020-06-24 01:24
Here's what you've asked for :) Thanks!

```python
# Starting in world World

[21:22:02 INFO]: HiRANDY2 issued server command: /creativeplots
[21:22:06 INFO]: [StayPut] onPlayerTeleportEvent COMMAND
[21:22:06 INFO]: [StayPut] Saving HiRANDY2 (a50b2d7a-73ea-40bc-8b9a-5f293ea89df2)'s location in >world<
[21:22:06 INFO]: [StayPut] HiRANDY2: world --> cplots2
[21:22:06 INFO]: [StayPut] Not redirecting teleport because the destination appears to be specific location in the world
[21:22:06 INFO]: [StayPut] Location{world=CraftWorld{name=cplots2},x=-185.5,y=75.0,z=-0.5,pitch=0.0,yaw=0.0} != Location{world=null,x=-185.96871714079504,y=76.0,z=0.32145280053448155,pitch=4.7017703,yaw=0.9931705}
[21:22:06 INFO]: [Multiverse-Core-Debug] Got teleport event for player 'HiRANDY2' with cause 'COMMAND'
[21:22:06 INFO]: [Multiverse-Core-Debug] Inferred sender 'null' from name 'null', fetched from name 'HiRANDY2'
[21:22:06 INFO]: [Multiverse-Core-Debug] Player 'HiRANDY2' was allowed to go to 'cplots' because enforceaccess is off.
[21:22:06 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'HiRANDY2' to go to 'cplots'.
[21:22:06 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2 traveling from world: world to world: cplots2 ===
[21:22:06 INFO]: [Multiverse-Inventories-Debug] No groups for toWorld.
[21:22:06 INFO]: [Multiverse-Inventories-Debug] Change affected by 2 fromProfiles and 1 toProfiles
[21:22:06 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy
[21:22:06 INFO]: [Multiverse-Inventories-Debug] Persisted: ender_chest, inventory_contents, armor_contents, off_hand, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, last_location, potion_effects to WORLD:world (ProfileType:SURVIVAL) for player HiRANDY2
[21:22:06 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy
[21:22:06 INFO]: [Multiverse-Inventories-Debug] got data folder: plugins/Multiverse-Inventories/worlds/world from type: WORLD
[21:22:06 INFO]: [Multiverse-Inventories-Debug] Persisted: hit_points, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand to GROUP:survival (ProfileType:SURVIVAL) for player HiRANDY2
[21:22:06 INFO]: [StayPut] onPlayerTeleportEvent PLUGIN
[21:22:06 INFO]: [StayPut] Not saving location because player did not jump worlds
[21:22:06 INFO]: [StayPut] HiRANDY2: cplots2 --> cplots2
[21:22:06 INFO]: [StayPut] Not redirecting teleport because player did not jump worlds
[21:22:06 INFO]: [Multiverse-Core-Debug] Got teleport event for player 'HiRANDY2' with cause 'PLUGIN'
[21:22:06 INFO]: [Multiverse-Core-Debug] Inferred sender 'null' from name 'null', fetched from name 'HiRANDY2'
[21:22:06 INFO]: [Multiverse-Core-Debug] Player 'HiRANDY2' is teleporting to the same world.
[21:22:06 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'HiRANDY2' to go to 'cplots'.
[21:22:06 INFO]: [Multiverse-Inventories-Debug] got data folder: plugins/Multiverse-Inventories/groups/survival from type: GROUP
[21:22:06 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy
[21:22:06 INFO]: [Multiverse-Inventories-Debug] Updated: ender_chest, inventory_contents, armor_contents, off_hand, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, last_location, potion_effects for HiRANDY2 for WORLD:cplots2 (ProfileType:SURVIVAL)
[21:22:06 INFO]: [Multiverse-Inventories-Debug] Defaulted: bed_spawn for HiRANDY2 for WORLD:cplots2 (ProfileType:SURVIVAL)
[21:22:06 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2's WORLD_CHANGE handling complete! ===
[21:22:06 INFO]: [Multiverse-Core-Debug] Handling gamemode for player: HiRANDY2, Changing to CREATIVE
[21:22:06 INFO]: [Multiverse-Core-Debug] From World: CraftWorld{name=cplots2}
[21:22:06 INFO]: [Multiverse-Core-Debug] To World: {"MVWorld@817665717":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"cplots2"}}
> 
>  # Now, in creativeplots, issue command /lobby
> 
[21:22:22 INFO]: HiRANDY2 issued server command: /lobby
[21:22:22 INFO]: [StayPut] onPlayerTeleportEvent PLUGIN
[21:22:22 INFO]: [StayPut] Saving HiRANDY2 (a50b2d7a-73ea-40bc-8b9a-5f293ea89df2)'s location in >cplots2<
[21:22:22 INFO]: [StayPut] HiRANDY2: cplots2 --> spawn
[21:22:22 INFO]: [StayPut] Not redirecting teleport because the destination appears to be specific location in the world
[21:22:22 INFO]: [StayPut] Location{world=CraftWorld{name=spawn},x=87.5,y=25.0,z=12.5,pitch=-2.1056118,yaw=-180.35959} != Location{world=null,x=87.48729771974298,y=25.0,z=12.523983635340153,pitch=39.450027,yaw=-0.8496704}
[21:22:22 INFO]: [Multiverse-Core-Debug] Got teleport event for player 'HiRANDY2' with cause 'PLUGIN'
[21:22:22 INFO]: [Multiverse-Core-Debug] Inferred sender 'null' from name 'null', fetched from name 'HiRANDY2'
[21:22:22 INFO]: [Multiverse-Core-Debug] Player 'HiRANDY2' was allowed to go to 'spawn' because enforceaccess is off.
[21:22:22 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'HiRANDY2' to go to 'spawn'.
[21:22:22 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2 traveling from world: cplots2 to world: spawn ===
[21:22:22 INFO]: [Multiverse-Inventories-Debug] No groups for fromWorld.
[21:22:22 INFO]: [Multiverse-Inventories-Debug] Change affected by 1 fromProfiles and 1 toProfiles
[21:22:22 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy
[21:22:22 INFO]: [Multiverse-Inventories-Debug] Persisted: ender_chest, inventory_contents, armor_contents, off_hand, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, last_location, potion_effects to WORLD:cplots2 (ProfileType:SURVIVAL) for player HiRANDY2
[21:22:22 INFO]: [Multiverse-Inventories-Debug] got data folder: plugins/Multiverse-Inventories/worlds/cplots2 from type: WORLD
[21:22:22 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy

# The spurious event ensues 

[21:22:22 INFO]: [StayPut] onPlayerTeleportEvent PLUGIN
[21:22:22 INFO]: [StayPut] Saving HiRANDY2 (a50b2d7a-73ea-40bc-8b9a-5f293ea89df2)'s location in >spawn<
[21:22:22 INFO]: [StayPut] HiRANDY2: spawn --> world
[21:22:22 INFO]: [StayPut] Not redirecting teleport because the destination appears to be specific location in the world
[21:22:22 INFO]: [StayPut] Location{world=CraftWorld{name=world},x=54.25103920956476,y=65.5,z=-15.488323914068044,pitch=-16.801744,yaw=270.259} != Location{world=null,x=45.5,y=66.0,z=-15.5,pitch=-6.814348,yaw=-88.26306}
[21:22:22 INFO]: [Multiverse-Core-Debug] Got teleport event for player 'HiRANDY2' with cause 'PLUGIN'
[21:22:22 INFO]: [Multiverse-Core-Debug] Inferred sender 'null' from name 'null', fetched from name 'HiRANDY2'
[21:22:22 INFO]: [Multiverse-Core-Debug] Player 'HiRANDY2' was allowed to go to 'world' because enforceaccess is off.
[21:22:22 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'HiRANDY2' to go to 'world'.
[21:22:23 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2 traveling from world: spawn to world: world ===
[21:22:23 INFO]: [Multiverse-Inventories-Debug] Change affected by 1 fromProfiles and 0 toProfiles
[21:22:23 INFO]: [Multiverse-Inventories-Debug] No toProfiles...
[21:22:23 INFO]: [Multiverse-Inventories-Debug] Ignoring optional share: economy
[21:22:23 INFO]: [Multiverse-Inventories-Debug] Persisted: ender_chest, inventory_contents, armor_contents, off_hand, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, last_location, potion_effects to WORLD:spawn (ProfileType:SURVIVAL) for player HiRANDY2
[21:22:23 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2's WORLD_CHANGE handling complete! ===
[21:22:23 INFO]: [Multiverse-Inventories-Debug] got data folder: plugins/Multiverse-Inventories/worlds/spawn from type: WORLD
[21:22:23 INFO]: [Multiverse-Inventories-Debug] Updated: hit_points, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand for HiRANDY2 for GROUP:survival (ProfileType:SURVIVAL)
[21:22:23 INFO]: [Multiverse-Inventories-Debug] Defaulted: bed_spawn for HiRANDY2 for GROUP:survival (ProfileType:SURVIVAL)
[21:22:23 INFO]: [Multiverse-Inventories-Debug] === HiRANDY2's WORLD_CHANGE handling complete! ===
[21:22:23 INFO]: [Multiverse-Core-Debug] Handling gamemode for player: HiRANDY2, Changing to SURVIVAL
[21:22:23 INFO]: [Multiverse-Core-Debug] From World: CraftWorld{name=world}
[21:22:23 INFO]: [Multiverse-Core-Debug] To World: {"MVWorld@138240882":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}
[21:22:23 INFO]: [Multiverse-Core-Debug] Handling gamemode for player: HiRANDY2, Changing to SURVIVAL
[21:22:23 INFO]: [Multiverse-Core-Debug] From World: CraftWorld{name=world}
[21:22:23 INFO]: [Multiverse-Core-Debug] To World: {"MVWorld@138240882":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}

```

**Comment by pmdevita** [comment] 2020-06-24 01:48
So it's this second teleport out of `spawn` that shouldn't be happening right? It doesn't look like it's being caused by StayPut, it's saving previous locations in each world but it didn't actually interfere with any of the teleports in the log. What other plugins are you using? 

Also, what plugin did you use to set your spawn? It looks like there might be an additional problem where StayPut will not redirect any teleports due to it thinking the spawn is somewhere else (I can explain if you want, it's a bit complicated though).

**Comment by elsell** [comment] 2020-06-24 05:04
I have quite the list of plugins :fearful: 

```python
ActionHealth*, AdvancedBan*, AdvancedNMotd*, AdvancedPortals, AltFinder, AsyncWorldEdit, AuthMe, AutoMessager, 
BetterRTP, BiomeFinder*, BlocksHub, BountifulAPI, BountyHunters, Citizens, ClearLag, CoreProtect, CrazyCrates, 
CrazyEnchantments, DeluxeHub, DeluxeMentions*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsGeoIP, 
EssentialsProtect, EssentialsSpawn, eZProtector, Factions, FastLeafDecay, Graves, HolographicDisplays, HungerGames, Images, 
IridiumSkyblock, JoinEventsPro, JumpPads, KeepChunks, LibsDisguises, LuckPerms, MassiveCore, mcMMO, MobArena, 
Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, Paintball, Parkour, PlaceholderAPI, PlayerHeads, Playtimes*, 
PlotSquared, ProtocolLib, pvparena, PvPManager, Racing, RemoveWanders, RestrictedCreative, SignShopHelper, 
SimpleRename, StayPut, TAB, UltraCosmetics, UsefulWanderingTrader, Vault, ViewDistanceTweaks, VoidSpawn, Votifier, 
WorldCommand*, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

```
I'm using DeluxeHub to do the main Lobby spawn, and Essentials or Multiverse for the rest...It's a bit unclear to me how the precedence works and I wish there was a good way to debug this sort of thing (maybe there is, I'm a noob then :smiley: )

**Comment by pmdevita** [comment] 2020-06-24 14:27
One more thing, does the double teleport still happen if you remove StayPut? I'll look into adding support for Essentials set spawns

**Comment by pmdevita** [comment] 2020-06-24 15:55
Actually, it looks like Essentials doesn't have a feature for setting world spawn. What command did you use to set the spawn location of each world?

**Comment by elsell** [comment] 2020-06-25 01:15
> What command did you use to set the spawn location of each world?
` /mv set spawn`

> One more thing, does the double teleport still happen if you remove StayPut? 
I'll check and get back to you

Another note, what is the functionality of `blacklisted-worlds`? I thought it means that those worlds listed in the blacklist are safe from StayPut teleporting players, but I'm not experiencing that behavior.

**Comment by elsell** [comment] 2020-06-25 02:31
Alright, I've spent some more time debugging and I think in the end it may have been user error (so sorry).

Here's what I know:

Multiverse-Inventories *also* has things called `optional_shares`, one of which is `last_location`. If one enables this by typing `/mvinv toggle last_location`, players will teleport to their last location when entering a world. 

The behavior of this is pretty strict and seems to override other plugins that teleport between worlds (without StayPut enabled, my Paintball plugin couldn't seem to get me to the correct location as Multiverse would always TP me to my previous location.)

Thus the solution was to DISABLE `last_location` sharing by typing `/mvinv toggle last_location`. This prevents Multiverse-Inventories from bothering to teleport players to their previous location and lets StayPut do its job [well].

I'm still not entirely sure why the double-teleport was happening, but it does not happen after taking the aforementioned steps.

> Another note, what is the functionality of blacklisted-worlds? I thought it means that those worlds listed in the blacklist are safe from StayPut teleporting players, but I'm not experiencing that behavior.

Disregard this ignorant statement. I incorrectly assumed that StayPut was the one teleporting me when it was Multiverse-Inventories. *Could you imagine how surprised I was to find out that a plugin that deals with INVENTORIES was the issue? xD*


I will continue my testing to ensure that this was indeed the issue, and I thank you greatly for your time spent assisting me and developing StayPut.

**Comment by pmdevita** [comment] 2020-06-25 04:05
Your welcome, glad you were able to make it work! Also thanks for telling me how you fixed it, I'll probably document it somewhere for other users.

I'm going to close the issue but if the problems come back feel free to open it up again.

**Closed by pmdevita** 2020-06-25 04:05 UTC
